# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ANANYA SHARMA
email: ananyasharma.iitkgp@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sharma2ananya.github.io" # the base hostname & protocol for your site
twitter_username: ananya
github_username:  sharma2ananya

permalink:  none

# Build settings
markdown: kramdown

# /:categories/:title.html
permalink: none

# URLS
link_to:
  facebook:        https://www.facebook.com/ananay.sharma
  github:          https://github.com/sharma2ananya
  twitter:         https://twitter.com/ANANYAS09783453
  linkedin:        https://www.linkedin.com/in/ananya-sharma-830480152/
  cocoa_all_pods:  https://cocoapods.org/owners/7316
  itunes_all_apps: https://itunes.apple.com/us/developer/kaunteya-suryawanshi/id927381428
  github_profile_pic: https://avatars1.githubusercontent.com/u/64925038?s=400&u=d421d2dd876e6e6f82c768f9a3e3b803e228b05f&v=4
